/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Estudiante_GUI;

import javax.swing.JOptionPane;

public class GUI_Estudiante extends javax.swing.JFrame {

    int Documento;
    String Nombres = "Null";
    String Apellidos = "Null";
    String Fecha_Nacimiento = "Null";
    String Carrera = "Null";
    String Semestre = "Null";
    
    Estudiante est = new Estudiante();
    
    public GUI_Estudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Documentotxt = new javax.swing.JTextField();
        Nombrestxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Apellidostxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Carreratxt = new javax.swing.JComboBox<>();
        Semestretxt = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Mostrarboton = new javax.swing.JButton();
        Nacimientotxt = new javax.swing.JTextField();
        Crearboton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setText("ESTUDIANTE");

        jLabel2.setText("DOCUMENTO:");

        Documentotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentotxtActionPerformed(evt);
            }
        });

        Nombrestxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombrestxtActionPerformed(evt);
            }
        });

        jLabel3.setText("NOMBRES:");

        Apellidostxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidostxtActionPerformed(evt);
            }
        });

        jLabel4.setText("APELLIDOS:");

        jLabel5.setText("F. NACIMIENTO");

        jLabel6.setText("CARRERA:");

        jLabel7.setText("SEMESTRE:");

        Carreratxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administración de Empresas", "Ingeniería Industrial", "Psicología", "Contabilidad", "Derecho", "Biología", "Ingeniería Civil", "Comunicación", "Educación", "Medicina", "Arquitectura", "Sociología", "Química", "Ciencias de la Computación", "Marketing", "Trabajo Social", "Fisioterapia", "Ciencias Políticas", "Farmacia" }));
        Carreratxt.setToolTipText("\n");

        Semestretxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEMESTRE 1", "SEMESTRE 2", "SEMESTRE 3", "SEMESTRE 4", "SEMESTRE 5", "SEMESTRE 6", "SEMESTRE 7", "SEMESTRE 8", "SEMESTRE 9", "SEMESTRE 10", " " }));
        Semestretxt.setToolTipText("\n");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel8.setText("ESCOLAR");

        Mostrarboton.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        Mostrarboton.setText("MOSTRAR");
        Mostrarboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarbotonActionPerformed(evt);
            }
        });

        Nacimientotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NacimientotxtActionPerformed(evt);
            }
        });

        Crearboton.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        Crearboton.setText("CREAR");
        Crearboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearbotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1))
                .addGap(42, 135, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(Semestretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Carreratxt, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(44, 44, 44))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(jLabel2)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Apellidostxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nombrestxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Documentotxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nacimientotxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Crearboton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Mostrarboton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Documentotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombrestxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellidostxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Nacimientotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Carreratxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Semestretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mostrarboton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Crearboton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DocumentotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DocumentotxtActionPerformed

    private void NombrestxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombrestxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombrestxtActionPerformed

    private void ApellidostxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidostxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidostxtActionPerformed

    private void MostrarbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarbotonActionPerformed

        est.MostrarDatos();

    }//GEN-LAST:event_MostrarbotonActionPerformed

    private void NacimientotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NacimientotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NacimientotxtActionPerformed

    private void CrearbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearbotonActionPerformed
        
        
        try {
            
            Documento = Integer.parseInt(Documentotxt.getText());
            Nombres = Nombrestxt.getText();
            Apellidos = Apellidostxt.getText();
            Fecha_Nacimiento = Nacimientotxt.getText();
            Carrera = Carreratxt.getSelectedItem().toString();
            Semestre = Semestretxt.getSelectedItem().toString();
            
            if (Documento == 0||Nombres == "Null"||Apellidos == "Null"||Fecha_Nacimiento == "Null"||Carrera == "Null"||Semestre == "Null"){
                
                JOptionPane.showMessageDialog(null, "Por favor, Rellene todos los campos del formulario");
            } else {
                
                JOptionPane.showMessageDialog(null, "Registro Completado Exitosamente");
                
                est.setDocumento(Documento);
                est.setNombres(Nombres);
                est.setApellidos(Apellidos);
                est.setFecha_Nacimiento(Fecha_Nacimiento);
                est.setCarrera(Carrera);
                est.setSemestre(Semestre);
        
            }
            
        } catch (NumberFormatException e){
        
            JOptionPane.showMessageDialog(null, "Error, Formato Invalido");
        
        } catch (Exception a) {
            
            JOptionPane.showMessageDialog(null, "Error, revise el formato de la información");
        }
    }//GEN-LAST:event_CrearbotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Estudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellidostxt;
    private javax.swing.JComboBox<String> Carreratxt;
    private javax.swing.JButton Crearboton;
    private javax.swing.JTextField Documentotxt;
    private javax.swing.JButton Mostrarboton;
    private javax.swing.JTextField Nacimientotxt;
    private javax.swing.JTextField Nombrestxt;
    private javax.swing.JComboBox<String> Semestretxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
